In this simple assignment, you will experiment with a toy dataset - the
Iris dataset.

In [110]:
#importing the required libraries
import numpy as np
from sklearn import datasets
import pandas as pd

(a) Load the Iris dataset (2 points).

In [111]:
#load the iris dataset
iris_dataset = datasets.load_iris()
print(iris_dataset)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

(b) The Iris data has 3 classes. For the purposes of this assignment, you will modify the dataset so that it has 2 classes - specifically, you will merge the setosa and the versicolor classes (2 points)

In [112]:
#let's merge the two classes
pos = 0 #a variable to get the postition in the target sub-array
for i in iris_dataset['target']:
    if (i==0):
        iris_dataset['target'][pos] = 1
    pos = pos + 1


In [113]:
print(iris_dataset['target'])

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


(c) Construct a training set and a testing set using an 80 - 20 split using random sampling (3 points).

In [114]:
#We only need the data and target column of the iris dictionary
keys_required = ["data","target"]
iris_dataset_subset = {key:iris_dataset[key] for key in keys_required}
print(iris_dataset_subset)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [115]:
#convert iris dictionary to a datframe
iris_df = pd.DataFrame(data = iris_dataset_subset['data'], columns = ['Sepal Length','Sepal Width','Petal Length','Petal Width'])

In [116]:
iris_df

Sepal Length  Sepal Width  Petal Length  Petal Width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [117]:
#append the target column of the dictionary to the above dataframe
iris_df ['Type'] = iris_dataset_subset['target']

In [118]:
print(iris_df)
print(iris_df['Type'].value_counts()) #check if there are 100 in type 1 and 50 in type 2

     Sepal Length  Sepal Width  Petal Length  Petal Width  Type
0             5.1          3.5           1.4          0.2     1
1             4.9          3.0           1.4          0.2     1
2             4.7          3.2           1.3          0.2     1
3             4.6          3.1           1.5          0.2     1
4             5.0          3.6           1.4          0.2     1
..            ...          ...           ...          ...   ...
145           6.7          3.0           5.2          2.3     2
146           6.3          2.5           5.0          1.9     2
147           6.5          3.0           5.2          2.0     2
148           6.2          3.4           5.4          2.3     2
149           5.9          3.0           5.1          1.8     2

[150 rows x 5 columns]
1    100
2     50
Name: Type, dtype: int64


In [119]:
#we are going to shuffle the rows of the datframe to get randomised training and test set
iris_df_shuffled = iris_df.sample(frac = 1)

In [120]:
print(iris_df_shuffled)

     Sepal Length  Sepal Width  Petal Length  Petal Width  Type
81            5.5          2.4           3.7          1.0     1
126           6.2          2.8           4.8          1.8     2
95            5.7          3.0           4.2          1.2     1
24            4.8          3.4           1.9          0.2     1
106           4.9          2.5           4.5          1.7     2
..            ...          ...           ...          ...   ...
77            6.7          3.0           5.0          1.7     1
26            5.0          3.4           1.6          0.4     1
59            5.2          2.7           3.9          1.4     1
17            5.1          3.5           1.4          0.3     1
136           6.3          3.4           5.6          2.4     2

[150 rows x 5 columns]


In [121]:
#now lets create our training and test sets
df_length = (len(iris_df))
df_train_length = int(df_length*0.8)
iris_df_train = iris_df_shuffled[0:df_train_length]
iris_df_test = iris_df_shuffled[df_train_length:df_length]

#changing the parameters to X and Y for simplicity X-> input, Y-> output
X_train = iris_df_train[['Sepal Length','Sepal Width','Petal Length','Petal Width']]
Y_train = iris_df_train['Type']
X_test = iris_df_test[['Sepal Length','Sepal Width','Petal Length','Petal Width']]
Y_test = iris_df_test['Type']

(d) Use Logistic Regression as a black-box classifier and asses the performance (4 points).

In [122]:
#use in built logistic regression from sklearn
from sklearn.linear_model import LogisticRegression
LogReg = LogisticRegression() #assingning the Logistic Regression classifier as LogReg
LogReg.fit(X_train, Y_train)


LogisticRegression()

In [123]:
#let's see what our machine predicts
predictions = LogReg.predict(X_test)
print(predictions)


[1 1 2 2 2 2 1 1 1 1 1 1 2 2 1 1 2 2 1 1 1 1 1 1 2 2 1 1 1 2]


In [124]:
#let's check the accuracy of our predictions using a confusion matrix and accuracy score
from sklearn.metrics import confusion_matrix
cfm = confusion_matrix(Y_test,predictions)
print(cfm)
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(Y_test,predictions)
print(accuracy)

[[19  1]
 [ 0 10]]
0.9666666666666667


(e) Implement stratified sampling, again using 80% of the data for training and 20% of the data for testing. Decide the stratification variable and explain your choice (4 points).

In [125]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(iris_df.drop('Type',axis = 1),iris_df['Type'],test_size = 0.2, random_state = 42,stratify = iris_df['Type'])
LogReg = LogisticRegression()
LogReg.fit(X_train, Y_train)

LogisticRegression()

The stratification variable will be the target variable (y component) which in this case is Type (`iris_df['Type]`). In random sampling there might be situations where the random sample is not representative of our orignal data. Stratifying addresses this issue. The  argument `stratify` tells the `train_test_split()` to stratify the target variable `iris_df['Type']` which ensures that the sample obtained is more representative of the full sample. Here we have 100 (2/3) observations from type I and 50 (1/3) from type 2. Since this data is imbalanced, startification will help us in ensuring that we have a balanced dataset such that both the train and test sets have observations in the same ration as was in the original dataset. So train dataset and test data set will each have 2/3 from type 1 and 1/3 from type 2.

In [126]:
#let's see what the predictions are in this case
predictions = LogReg.predict(X_test)
print(predictions)

[1 2 1 1 1 1 1 1 2 1 2 2 2 1 1 1 1 1 1 2 1 2 1 2 2 1 1 1 2 1]


In [127]:
#let's see what the confusion matrxix and accuracy score looks like in this case
from sklearn.metrics import confusion_matrix
cfm = confusion_matrix(Y_test,predictions)
print(cfm)
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(Y_test,predictions)
print(accuracy)

[[20  0]
 [ 0 10]]
1.0


(f) Re-assess the performance. Comment on any changes from the random sampling case. If there is no significant change, comment
on why not (2 points).

Yes there is a difference between the random sampling case and the stratified sampling case. The confusion matrices and accuracy scores clearly indicate that. There is an accuracy score difference of almost 0.04-0.06 (depending on the run), which in many Machine Learning cases is quite significant. In some runs this difference is 0, but it happens only a few times.  Stratified sampling preserves class propotion. What it means is that if Y (target variable of orignal dataset) has 20% from class 1 and 80% from class 2, Y_train and Y_test will each also have 20% from class 1, 80% from class 2. Stratified sampling makes the model more realistic. This method is especially useful when there is a class imbalance. In our dataset there are 100 datasets from type 1 and 50 from type 2. So there is a class imbalance. In cases where the random sampling ends up taking training and test datasets where classes are in the same propotion as orignal dataset random sampling becomes equivalent to stratified sampling.

#### End